
# config/routes/annotations.yaml
controllers:
    resource: ../src/Controller/
    type: annotation

admin_donations_recherche:
    path: /Admin/Donation/recherche
    controller: ../src/Controller/DonationAdminController::recherche
    methods: ['GET']